"""Add users table

Revision ID: 113c09388f90
Revises: 39db6729dbde
Create Date: 2018-11-29 16:23:22.095928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113c09388f90'
down_revision = '39db6729dbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=280), nullable=True),
    sa.Column('api_token', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
